spring.application.name=app

# ===================================
# PostgreSQL + Hibernate (JPA) - NeonTech
# ===================================
# Las credenciales están en application-secrets.properties (excluido de Git)

spring.datasource.url=ep-polished-frost-antn533h-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mrDq0F3PUJyz
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect